apiVersion: v1
kind: Service
metadata:
  name:  learnwise-payment-service
spec:
  selector:
    app: payment-service
  ports:
  - name:  payment-service
    protocol: TCP
    port:  4005
    targetPort: 4005

    