apiVersion: v1
kind: Service
metadata:
  name:  learnwise-user-service
spec:
  selector:
    app: user-service
  ports:
  - name:  user-service
    protocol: TCP
    port:  4002
    targetPort: 4002
    