apiVersion: apps/v1
kind: Deployment
metadata:
  name: learnwise-payment-deployment
  labels:
    name:  payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - image: rithickramanthali/learnwise-payment:latest
        name: payment-service
        ports:
        - containerPort: 4005
        envFrom:
          - configMapRef:
              name: payment-service-config