apiVersion: apps/v1
kind: Deployment
metadata:
  name: learnwise-user-deployment
  labels:
    name:  user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - image: rithickramanthali/learnwise-user:latest
        name: user-service
        ports:
        - containerPort: 4002
        envFrom:
          - configMapRef:
              name: user-service-config